name: Update Coverage Badge

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  update-badge:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE20: true

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install pipenv
          pipenv install --dev

      - name: Run tests with coverage
        run: |
          pipenv run pytest --cov=src --cov-report=xml

      - name: Generate Shields.io badge link
        id: generate_badge
        run: |
          coverage_badge=$(pipenv run python generate_shields_badge.py)
          echo "$coverage_badge" > badge.txt

      - name: Update README.md with new coverage badge
        run: |
          badge_url=$(cat badge.txt)
          sed -i "s|!\[Coverage Badge\](.*)|$badge_url|" README.md

      # Commit and push changes
      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

          # Add the modified files
          git add README.md

          # Commit the changes
          git commit -m "ci(github-actions): update coverage badge"

          # Push the changes back to the branch
          git push origin HEAD:${{ github.head_ref || github.ref_name }}
